// <auto-generated />
using System;
using FichaMedica.Datos;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FichaMedica.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    [Migration("20250620012444_PrimeraSubida")]
    partial class PrimeraSubida
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("FichaMedica.Modelos.Ficha", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Alergias")
                        .HasColumnType("longtext");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Dni")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Enfermedades")
                        .HasColumnType("longtext");

                    b.Property<bool>("EsAlergico")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("EsDiabetico")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("FechaNacimiento")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("GrupoSanguineo")
                        .HasColumnType("longtext");

                    b.Property<string>("MedicacionActual")
                        .HasColumnType("longtext");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("NombreContactoEmergencia")
                        .HasColumnType("longtext");

                    b.Property<string>("Sexo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("TelefonoContactoEmergencia")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Fichas");
                });
#pragma warning restore 612, 618
        }
    }
}
