// <auto-generated />
using System;
using FichaMedica.Datos;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FichaMedica.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    [Migration("20250629154516_SeAgreganCambiosEnElModelo")]
    partial class SeAgreganCambiosEnElModelo
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("FichaMedica.Modelos.Ficha", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("AceptaTerminos")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Alergia")
                        .HasColumnType("longtext");

                    b.Property<string>("AlergiasDetalle")
                        .HasColumnType("longtext");

                    b.Property<int?>("AlturaCm")
                        .HasColumnType("int");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("CirugiaReciente")
                        .HasColumnType("longtext");

                    b.Property<string>("CirugiaRecienteDetalle")
                        .HasColumnType("longtext");

                    b.Property<string>("CondicionCronica")
                        .HasColumnType("longtext");

                    b.Property<string>("CondicionesCronicasDetalle")
                        .HasColumnType("longtext");

                    b.Property<string>("Dni")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Droga")
                        .HasColumnType("longtext");

                    b.Property<string>("DrogaDetalle")
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("FechaNacimiento")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Fuma")
                        .HasColumnType("longtext");

                    b.Property<string>("FumaDetalle")
                        .HasColumnType("longtext");

                    b.Property<string>("GrupoSanguineo")
                        .HasColumnType("longtext");

                    b.Property<string>("InformacionAdicional")
                        .HasColumnType("longtext");

                    b.Property<string>("MedicacionRegular")
                        .HasColumnType("longtext");

                    b.Property<string>("MedicacionRegularDetalle")
                        .HasColumnType("longtext");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("NombreContactoEmergencia")
                        .HasColumnType("longtext");

                    b.Property<decimal?>("PesoKg")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("Sexo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Telefono")
                        .HasColumnType("longtext");

                    b.Property<string>("TelefonoContactoEmergencia")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Fichas");
                });
#pragma warning restore 612, 618
        }
    }
}
